---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2

verifier:
  name: inspec
  format: doc

require_chef_omnibus: 12.9.38

suites:
  - name: tomberi
    run_list:
      - recipe[tomberi::ntp]
      - recipe[tomberi::nginx]
      - recipe[tomberi::munin]
    attributes:
