---
driver:
  name: dokken
  chef_version: latest

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
  - name: debian-8
    driver:
      image: debian:8
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y lsb-release procps net-tools
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

suites:
  - name: tomberi
    run_list:
      - recipe[tomberi::apt]
      - recipe[tomberi::ntp]
      - recipe[tomberi::nginx]
      - recipe[tomberi::munin]
    attributes:
