---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2

verifier:
  name: inspec

require_chef_omnibus: 12.6.0

suites:
  - name: tomberi
    run_list:
      - recipe[tomberi::ntp]
      - recipe[tomberi::nginx]
    attributes:
